name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - linux-X86
        - linux-ARM
        - macos-X86
        - macos-ARM
        - windows-X64
        include:
        - build: linux-X86
          os: ubuntu-22.04
          cc: gcc
          arch: x86_64
        - build: linux-ARM
          os: ubuntu-22.04
          cc: gcc
          arch: arm
        - build: macos-X86
          os: macos-12
          cc: gcc
          arch: x86_64
        - build: macos-ARM
          os: macos-12
          cc: gcc
          arch: arm
        - build: windows-X64
          os: windows-latest
          cc: gcc
          arch: x86_64

    env:
      CI_TARGET_BUILD: ${{ matrix.build }}
      CI_TARGET_ARCH: ${{ matrix.arch }}
      CC: ${{ matrix.cc }}

    steps:
    - name: git config line endings (Windows)
      if: ${{ contains( matrix.build, 'windows' ) }}
      run: git config --global core.autocrlf input
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install Cygwin toolchain (Windows)
      if: ${{ startsWith(matrix.build, 'windows-cygwin') }}
      uses: cygwin/cygwin-install-action@master
      with:
        packages: >
          mingw64-${{matrix.arch}}-binutils
          mingw64-${{matrix.arch}}-CUnit
          mingw64-${{matrix.arch}}-curl
          mingw64-${{matrix.arch}}-dlfcn
          mingw64-${{matrix.arch}}-gcc-core
          mingw64-${{matrix.arch}}-headers
          mingw64-${{matrix.arch}}-runtime
          mingw64-${{matrix.arch}}-zlib

    - name: Install msys2 toolchain (Windows)
      if: ${{ startsWith(matrix.build, 'windows-msys2') }}
      uses: msys2/setup-msys2@v2
      with:
        install: >
          git
          base-devel
          mingw-w64-${{matrix.arch}}-clang
          mingw-w64-${{matrix.arch}}-cunit
          mingw-w64-${{matrix.arch}}-toolchain
          mingw-w64-${{matrix.arch}}-lld
          mingw-w64-${{matrix.arch}}-python-scipy
          mingw-w64-${{matrix.arch}}-python-six
          mingw-w64-${{matrix.arch}}-python-statsmodels
          mingw-w64-${{matrix.arch}}-python-sphinx

    - name: Install dependencies
      run: ${{matrix.shell}} ./ci/actions-install.sh
      if: ${{ !contains( matrix.build, 'msys2' ) }}
    - name: Build
      run:  ${{matrix.shell}} ./ci/actions-build.sh
    - name: Build installer (Windows)
      if: ${{ contains( matrix.build, 'windows' ) }}
      shell: cmd
      run: |
        cd os\windows
        dobuild.cmd ${{ matrix.installer_arch }}
        cd ..\..

    - name: Upload installer as artifact
      uses: actions/upload-artifact@v3
      
    - name: Remove dependency files to resolve Makefile Cygwin sed issue (Windows)
      if: ${{ startsWith(matrix.build, 'windows-cygwin') }}
      run: rm *.d */*.d */*/*.d
      shell: bash
    - name: Smoke test
      run:  ${{matrix.shell}} ./ci/actions-smoke-test.sh
    - name: Full test
      run:  ${{matrix.shell}} ./ci/actions-full-test.sh
